version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    versioning-strategy: increase
    commit-message:
      prefix: "*"
    groups:
      npm:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: ".github/workflows"
    groups:
      github-actions:
        patterns:
          - "*"
